### ISSUE TITLE
Crash after clicking Options

### ISSUE THREAD

**Issue by 0xhtml** [sduduzog/slim-launcher#105]
Slim Launcher is crashing when I click on Options.

Logs:

    og.slimlaunche: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
    AndroidRuntime: FATAL EXCEPTION: main
    AndroidRuntime: Process: com.sduduzog.slimlauncher, PID: 13379
    AndroidRuntime: java.lang.IllegalStateException: no current navigation node
    AndroidRuntime: 	at b.l.m.onClick(:10)
    AndroidRuntime: 	at android.view.View.performClick(View.java:6659)
    AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6631)
    AndroidRuntime: 	at android.view.View.access$3100(View.java:790)
    AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:26187)
    AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:907)
    AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
    AndroidRuntime: 	at android.os.Looper.loop(Looper.java:216)
    AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7625)
    AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
    AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

Device:

    [ro.product.CustCVersion]: [C432]
    [ro.product.board]: [ANE]
    [ro.product.brand]: [HUAWEI]
    [ro.product.cpu.abi]: [arm64-v8a]
    [ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
    [ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
    [ro.product.cpu.abilist64]: [arm64-v8a]
    [ro.product.device]: [HWANE]
    [ro.product.fingerprintName]: [HUAWEI-02ANE]
    [ro.product.first_api_level]: [26]

**Comment by ashutoshgngwr** [comment]
:+1: been facing this exact issue

**Comment by koppen37** [comment]
Look similar to the crash in #92.  If so, this should be fixed in the next release (2.4.16). Looks like a new version has been tagged, so I expect F-droid to show an update in the next few days, not sure about the play store.
