### ISSUE TITLE
Crash after theme change

### ISSUE THREAD

**Issue by koppen37** [sduduzog/slim-launcher#92]
I just noticed that the latest f-droid version (and master) seems to have a reproducible crash:

1. Open options from the homescreen
2. Change theme  -> select any theme
3. Press back
4. Try to open options again from the homescreen

Logcat gives me: 
````
07-27 11:12:12.125 29482 29482 E AndroidRuntime: FATAL EXCEPTION: main
07-27 11:12:12.125 29482 29482 E AndroidRuntime: Process: com.sduduzog.slimlauncher, PID: 29482
07-27 11:12:12.125 29482 29482 E AndroidRuntime: java.lang.IllegalStateException: no current navigation node
07-27 11:12:12.125 29482 29482 E AndroidRuntime:        at androidx.navigation.NavController.navigate(NavController.java:765)
07-27 11:12:12.125 29482 29482 E AndroidRuntime:        at androidx.navigation.NavController.navigate(NavController.java:745)
07-27 11:12:12.125 29482 29482 E AndroidRuntime:        at androidx.navigation.NavController.navigate(NavController.java:731)
07-27 11:12:12.125 29482 29482 E AndroidRuntime:        at androidx.navigation.Navigation$1.onClick(Navigation.java:119)
07-27 11:12:12.125 29482 29482 E AndroidRuntime:        at android.view.View.performClick(View.java:6294)
07-27 11:12:12.125 29482 29482 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:24770)
07-27 11:12:12.125 29482 29482 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
07-27 11:12:12.125 29482 29482 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
07-27 11:12:12.125 29482 29482 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
07-27 11:12:12.125 29482 29482 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
07-27 11:12:12.125 29482 29482 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-27 11:12:12.125 29482 29482 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
07-27 11:12:12.125 29482 29482 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
````

The previous f-droid version did not have this bug, furthermore the time format picker doesn't trigger the crash. 

I will try to find out which change first introduced this bug, but maybe you already have a clue why this happens.

**Comment by koppen37** [comment]
The crash happens from commit a5453862e10c437 onwards. 

After some searching I found that changing 
https://github.com/sduduzog/slim-launcher/blob/a8770859afa5e6ca931c2f15e056f7db408442de/app/build.gradle.kts#L78
to ` implementation("androidx.navigation:navigation-fragment-ktx:2.2.0")` solves the crash. 

However I have no clue whether changing this line has any further implications...

**Comment by jkuester** [comment]
+1  I tried upgrading to the androidx nav libraries and everything seemed to work fine!

**Comment by sduduzog** [comment]
Please check if this is sorted for v2.4.14, I try to keep dependencies up to date with most releases so this might have been addressed, I'm not sure

**Comment by koppen37** [comment]
F-droid version 2.4.14 (and current master) is still affected by this, since it still uses the navigation library from android instead of androidx. 

Note that #91 already includes this fix

**Comment by sduduzog** [comment]
Ahh well... Also now I'm waiting for 2.4.15 to pass review so that I can release it to F-Droid

**Comment by sduduzog** [comment]
So my latest build failed because the updates I brought included removing github pages which hosted the apps privacy policy. The fix for that will include one for this too
